#!/bin/bash
# build_kernel

# Author Name: Thomas Frantz
# Date Written: 09/10/2020
# Date Last Modified: 09/10/2020
# Purpose Of The Script: To build the kernel with the specifications of the 
#                        assignment

# Description: This script will execute the following steps in sequence
#           1. Checkout the required repositories (unix_a2 & linux)
#           2. Build the kernel with the right .config file
#           3. Make a bakcup of the kernel files, and move over the new files
#           4. Install the kernel & drivers

GIT=/usr/bin/git

exit_script () {
	# A helper function designed to exit with a custom message.
	echo "build_kernel failed with exit code: $?. $1"
	exit 1
}

confirm_exit_script () {
	# A helper function to propmt the user if they wish to exit. This
	# function can be used in cases where a failed command might not 
	# necessarily be fatal to the overall script.

	# Read in a response from the user
	read -r -p "The previous command has just failed (Exit Code: $?; $1). Do you wish to continue? [Y/n] " response
	
	# If the repsonse is yes or some variation of such, then continue on.
	# Otherwise, exit script as appropriate
	if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
	then
		echo "Continuing ..."
	else
		exit_script "$1"
	fi
}

# Clone the neccesary repositories.
$GIT clone git@github.com:Black-Tomcat/unix-ass-2.git || confirm_exit_script "Could not clone assignment repository"
$GIT clone --depth=1 git@github.com:raspberrypi/linux.git || confirm_exit_script "Could not clone linux repository"

# Install prerequisites.
sudo apt install raspberrypi-kernel-headers build-essential bc git wget bison flex libssl-dev make     

# Create .config file for linux. 
(cd linux;  KERNEL=kernel7; make bcm2709_defconfig || exit_script "make bcm2709_defconfig (.config) failed!")

# Install more prerequisites. TODO merge this with above prereqs.
sudo apt-get install qt5-\*-dev
(cd linux; make xconfig || exit_script "make xconfig failed!")
